### ISSUE TITLE
Some of the cron expressions are just returning default exp "* * * ? * * *"

### ISSUE THREAD

**Issue by itowk** [Fy-Rakotondrabe/cron_quartz_ts#1]
How to replicate:

```
var {formatDays} = require("cron-quartz-ts")

const result = formatDays({ type: 'lastDayOnMonth' }) 

console.log(result)
```

This returns:

"* * * ? * * *"

Attaching the pic as well:

<img width="828" alt="Screenshot 2024-02-05 at 11 34 40 AM" src="https://github.com/Fy-Rakotondrabe/cron-quartz-ts/assets/49436760/3e52142e-627f-4273-bfe6-160d7f891497">

**Comment by itowk** [comment]
Found the issue. The README has all types in camelcase however in the actual code, the types are all snake-case.

Would be helpful for others if the README is updated with the correct casing.

Eg: 
```const result = formatDays({ type: 'last_day_of_month' }) ```

Btw, thanks for this port!

**Comment by Fy-Rakotondrabe** [comment]
Hey
Thanks a bunch for spotting that issue and suggesting a fix! 🚀 I've reviewed the issue you raised, and I agree with your suggestion. I'll be working on fixing it shortly, If you have more ideas or find anything else, feel free to drop a note.

Cheers
